language: node_js

node_js:
  - "node"

cache:
  directories:
    - "node_modules"

install:
  - npm install -g pnpm
  - pnpm install
  
script:
  - pnpm run build

deploy:
  provider: pages
  keep-history: true
  skip-cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  on:
    branch: master